export const mockData = [
  {
    id: 1,
    author: "John Doe",
    created_at: new Date(),
    //created_at: new Date("2024-04-01"),
    content: "Hello World",
    isLike: false,
    likes: 0,
  },
  // {
  //   id: 2,
  //   author: "John Doe",
  //   //created_at: new Date("2024-03-26"),
  //   created_at: new Date("2024-04-26"),
  //   content: "Hello World2",
  //   isLike: false,
  //   likes: 2,
  // },
  // {
  //   id: 3,
  //   author: "John Doe",
  //   created_at: new Date("2024-04-20"),
  //   content:
  //     "Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3",
  //   isLike: true,
  //   likes: 14,
  // },
  // {
  //   id: 4,
  //   author: "John Doe",
  //   created_at: new Date("2024-04-10"),
  //   content: "Hello World",
  //   isLike: false,
  //   likes: 0,
  // },
  // {
  //   id: 5,
  //   author: "John Doe",
  //   //created_at: new Date("2024-03-26"),
  //   created_at: new Date("2024-04-26"),
  //   content: "Hello World2",
  //   isLike: false,
  //   likes: 2,
  // },
  // {
  //   id: 6,
  //   author: "John Doe",
  //   created_at: new Date("2024-03-20"),
  //   content:
  //     "Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3Hello World3",
  //   isLike: true,
  //   likes: 14,
  // },
];
